-- ----------------------------
-- Create database
-- ----------------------------
CREATE DATABASE IF NOT EXISTS `fino_cars` ;
USE `fino_cars`;

-- ----------------------------
-- Table structure for cars
-- ----------------------------
DROP TABLE IF EXISTS `cars`;
CREATE TABLE `cars` (
  `id` int(11) NOT NULL,
  `city_miles_per_gallon` int(11) NOT NULL,
  `classification` varchar(255) NOT NULL,
  `driveline` varchar(255) NOT NULL,
  `engine_type` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `fuel_type` varchar(255) NOT NULL,
  `highway_miles_per_gallon` int(11) NOT NULL,
  `horsepower` int(11) NOT NULL,
  `model_id` varchar(255) NOT NULL,
  `make` varchar(255) NOT NULL,
  `model_year` varchar(255) NOT NULL,
  `number_of_forward_gears` int(11) NOT NULL,
  `transmission` varchar(255) NOT NULL,
  `width` int(11) NOT NULL,
  `height` int(11) NOT NULL,
  `length` int(11) NOT NULL,
  `year` int(11) NOT NULL,
  `image_uri` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of cars
-- ----------------------------
BEGIN;
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (1, 10, 'Automatic transmission', 'Rear-wheel drive', 'Maybach 6.0L 12 Cylinder 620 hp 738 ft-lbs Turbo', 'MPV', 'Gasoline', 16, 620, '2011 Maybach 57 S', 'Maybach', '2011 Maybach 57', 5, '5 Speed Automatic Select Shift', 189, 1, 95, 2011, 'https://upload.wikimedia.org/wikipedia/en/7/7e/76_Pontiac_Astre.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (2, 13, 'Automatic transmission', 'Rear-wheel drive', 'Aston Martin 5.9L 12 Cylinder 490 hp 420 ft-lbs', 'Coupe', 'Gasoline', 18, 490, '2011 Aston Martin Virage Coup', 'Aston Martin', '2011 Aston Martin Virage Coup', 6, '6 Speed Automatic Select Shift', 113, 2, 96, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Ford_Crown_Victoria_LX.jpg/400px-Ford_Crown_Victoria_LX.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (3, 15, 'Manual transmission', 'Four-wheel drive', 'Jeep 3.8L 6 Cylinder 205 hp 240 ft-lbs', '4 WD', 'Gasoline', 19, 205, '2010 Jeep Wrangler Rubicon', 'Jeep', '2010 Jeep Wrangler', 6, '6 Speed Manual', 55, 8, 64, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Plymouth_Superbird.jpg/400px-Plymouth_Superbird.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (4, 23, 'Manual transmission', 'Front-wheel drive', 'Suzuki 2.0L 4 Cylinder 150 hp 140 ft-lbs', 'Sports', 'Gasoline', 33, 150, '2010 Suzuki SX4 Sport', 'Suzuki', '2010 Suzuki SX4 Sedan', 6, '6 Speed Manual', 193, 8, 138, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/2nd-Saab-9000-hatch.jpg/400px-2nd-Saab-9000-hatch.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (5, 15, 'Manual transmission', 'Four-wheel drive', 'Jeep 3.8L 6 Cylinder 202 hp 237 ft-lbs', 'Car', 'Gasoline', 19, 202, '2011 Jeep Wrangler Mojave', 'Jeep', '2011 Jeep Wrangler', 6, '6 Speed Manual', 79, 8, 41, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/2003-2005_Pontiac_Sunfire.jpg/400px-2003-2005_Pontiac_Sunfire.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (6, 16, 'Automatic transmission', 'Rear-wheel drive', 'Dodge 3.6L 6 Cylinder 290 hp 260 ft-lbs FFV', 'Classic', 'Gasoline', 23, 290, '2011 Dodge Durango Citadel', 'Dodge', '2011 Dodge Durango', 5, '5 Speed Automatic', 133, 9, 211, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/1971_AMC_Javelin_SST_red_Kenosha_street.JPG/400px-1971_AMC_Javelin_SST_red_Kenosha_street.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (7, 11, 'Manual transmission', 'Rear-wheel drive', 'Aston Martin 5.9L 12 Cylinder 510 hp 420 ft-lbs', 'Car', 'Gasoline', 17, 510, '2011 Aston Martin DBS Volante', 'Aston Martin', '2011 Aston Martin DBS Volante', 6, '6 Speed Manual', 113, 9, 112, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Jaguar_X-Type_Estate_front_20080731.jpg/400px-Jaguar_X-Type_Estate_front_20080731.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (8, 18, 'Manual transmission', 'Rear-wheel drive', 'BMW 3.0L 6 Cylinder 255hp 220 ft-lbs', 'Car', 'Gasoline', 28, 255, '2010 BMW Z4 Roadster sDrive30i', 'BMW', '2010 BMW Z4 Roadster', 6, '6 Speed Manual', 254, 10, 143, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/VW_Phaton_%282._Facelift%29_%E2%80%93_Frontansicht%2C_7._Mai_2011%2C_D%C3%BCsseldorf.jpg/400px-VW_Phaton_%282._Facelift%29_%E2%80%93_Frontansicht%2C_7._Mai_2011%2C_D%C3%BCsseldorf.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (9, 19, 'Manual transmission', 'Rear-wheel drive', 'Porsche 2.9L 6 Cylinder 255 hp 214 ft-lbs', 'Car', 'Gasoline', 27, 255, '2010 Porsche Boxster', 'Porsche', '2010 Porsche Boxster', 6, '6 Speed Manual', 8, 12, 19, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Pontiac_G6.jpg/400px-Pontiac_G6.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (10, 17, 'Automatic transmission', 'Front-wheel drive', 'Hyundai 3.8L 6 cylinder 260hp 257 ft-lbs', '4 WD', 'Gasoline', 23, 260, '2010 Hyundai Veracruz GLS', 'Hyundai', '2010 Hyundai Veracruz', 6, '6 Speed Automatic Select Shift', 153, 13, 233, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Ford500a.JPG/400px-Ford500a.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (11, 13, 'Automatic transmission', 'Rear-wheel drive', 'Rolls-Royce 6.6L 12 Cylinder 563 hp 575 ft-lbs', 'Car', 'Gasoline', 20, 563, '2010 Rolls-Royce Ghost', 'Rolls-Royce', '2010 Rolls-Royce Ghost', 8, '8 Speed Automatic Select Shift', 156, 13, 24, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/PontiacSolstice.jpg/400px-PontiacSolstice.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (12, 18, 'Manual transmission', 'Rear-wheel drive', 'Mercedes-Benz 3.0L 6 Cylinder 228 hp 221 ft-lbs', '2 WD', 'Gasoline', 26, 228, '2010 Mercedes-Benz SLK300', 'Mercedes', '2010 Mercedes-Benz SLK-Class', 6, '6 Speed Manual', 252, 17, 6, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Fiat_tipo_f.jpg/400px-Fiat_tipo_f.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (13, 17, 'Automatic transmission', 'Rear-wheel drive', 'Toyota 4.0L 6 Cylinder 260 hp 271 ft-lbs', 'Mini', 'Gasoline', 22, 260, '2010 Toyota FJ Cruiser', 'Toyota', '2010 Toyota FJ Cruiser', 5, '5 Speed Automatic', 113, 19, 63, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/1985-89_Plymouth_Reliant_K_LE.png/400px-1985-89_Plymouth_Reliant_K_LE.png');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (14, 19, 'Manual transmission', 'Rear-wheel drive', 'Porsche 2.9L 6 Cylinder 265 hp 221 ft-lbs', '4 WD', 'Gasoline', 27, 265, '2010 Porsche Cayman', 'Porsche', '2010 Porsche Cayman', 6, '6 Speed Manual', 8, 23, 24, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/1978_chevette.JPG/400px-1978_chevette.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (15, 19, 'Automatic transmission', 'Rear-wheel drive', 'BMW 3.0L 6 cylinder 300 hp 300 ft-lbs Turbo', 'Car', 'Gasoline', 28, 300, '2010 BMW 535i Gran Turismo', 'BMW', '2010 BMW 5 Series Gran Turismo', 8, '8 Speed Automatic Select Shift', 107, 23, 134, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Seat_Leon_1.4_TSI_Start%26Stop_Style_%28III%29_%E2%80%93_Frontansicht%2C_10._August_2013%2C_Ratingen.jpg/400px-Seat_Leon_1.4_TSI_Start%26Stop_Style_%28III%29_%E2%80%93_Frontansicht%2C_10._August_2013%2C_Ratingen.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (16, 15, 'Automatic transmission', 'Rear-wheel drive', 'Chevrolet 4.3L 6 Cylinder 195 hp 260 ft-lbs', 'Wagon', 'Gasoline', 20, 195, '2010 Chevrolet Express 1500', 'Chevrolet', '2010 Chevrolet Express', 4, '4 Speed Automatic', 224, 24, 60, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Chevrolet_Corsica_1994.jpg/400px-Chevrolet_Corsica_1994.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (17, 15, 'Automatic transmission', 'Rear-wheel drive', 'GMC 4.3L 6 Cylinder 195 hp 260 ft-lbs', 'Micro', 'Gasoline', 20, 195, '2010 GMC Savana Cargo 1500', 'GMC', '2010 GMC Savana', 4, '4 Speed Automatic', 224, 24, 60, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/1992_MX3_V6_24V.jpg/400px-1992_MX3_V6_24V.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (18, 17, 'Automatic transmission', 'Rear-wheel drive', 'Toyota 4.0L 6 Cylinder 270 hp 278 ft-lbs', 'Mini', 'Gasoline', 23, 270, '2010 Toyota 4Runner Limited', 'Toyota', '2010 Toyota 4Runner', 5, '5 Speed Automatic', 133, 24, 216, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/2000_TVR_Tuscan_4.0_Speed_Six_by_The_Car_Spy.jpg/400px-2000_TVR_Tuscan_4.0_Speed_Six_by_The_Car_Spy.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (19, 17, 'Automatic transmission', 'Front-wheel drive', 'Lincoln 3.7L 6 Cylinder 273 hp 270 ft-lbs.', '2 WD', 'Gasoline', 24, 273, '2010 Lincoln MKS', 'Lincoln', '2010 Lincoln MKS', 6, '6 Speed Automatic Select Shift', 135, 28, 64, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Aston_Martin_DB9_coupe_02.jpg/400px-Aston_Martin_DB9_coupe_02.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (20, 17, 'Automatic transmission', 'Front-wheel drive', 'Lincoln 3.7L 6 Cylinder 274 hp 270 ft-lbs', 'Vintage', 'Gasoline', 25, 274, '2012 Lincoln MKS', 'Lincoln', '2012 Lincoln MKS', 6, '6 Speed Automatic Select Shift', 135, 28, 64, 2012, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Pontiac_Catalina_front.jpg/400px-Pontiac_Catalina_front.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (21, 18, 'Manual transmission', 'All-wheel drive', 'Porsche 3.6L 6 cylinder 345 hp 288 ft-lbs', 'Car', 'Gasoline', 25, 345, '2010 Porsche 911 Carrera 4 Cabriolet', 'Porsche', '2010 Porsche 911 Cabriolet', 6, '6 Speed Manual', 16, 30, 108, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Oldsmobile_Toronado_0003.jpg/400px-Oldsmobile_Toronado_0003.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (22, 17, 'Manual transmission', 'Four-wheel drive', 'Jeep 3.6L 6 Cylinder 280 hp 260 lb-ft', 'Car', 'Gasoline', 21, 285, '2012 Jeep Wrangler  Call Of Duty MW3 Edition', 'Jeep', '2012 Jeep Wrangler', 6, '6 Speed Manual', 79, 34, 41, 2012, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Chrysler_Cirrus_--_01-27-2012.jpg/400px-Chrysler_Cirrus_--_01-27-2012.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (23, 18, 'Manual transmission', 'Rear-wheel drive', 'Nissan 3.7L 6 Cylinder 332 hp 270 ft-lbs', 'Coupe', 'Gasoline', 26, 332, '2009 Nissan 370Z Coupe', 'Nissan', '2009 Nissan 370Z Coupe', 6, '6 Speed Manual', 57, 35, 150, 2009, 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/VW_Corrado_-_standard.jpg/400px-VW_Corrado_-_standard.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (24, 18, 'Automatic transmission', 'Front-wheel drive', 'Kia 3.5L 6 Cylinder 271 hp 248 ft-lbs', 'Car', 'Gasoline', 25, 271, '2011 Kia Sedona EX', 'Kia', '2011 Kia Sedona', 6, '6 Speed Automatic Select Shift', 191, 36, 10, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Mercedes_R_350_CDI_4MATIC_Lang_%28V251%29_Facelift_front_20101017.jpg/400px-Mercedes_R_350_CDI_4MATIC_Lang_%28V251%29_Facelift_front_20101017.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (25, 10, 'Automatic transmission', 'Rear-wheel drive', 'Maybach 6.0L 12 Cylinder 604 hp 738 ft-lbs Turbo', 'Hybrid', 'Gasoline', 16, 604, '2009 Maybach Landaulet', 'Maybach', '2009 Maybach Landaulet', 5, '5 Speed Automatic Select Shift', 189, 38, 20, 2009, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Volvo_V50_1.6_D.jpg/400px-Volvo_V50_1.6_D.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (26, 10, 'Automatic transmission', 'Rear-wheel drive', 'Maybach 5.5L 12 Cylinder 543 hp 664 ft-lbs Turbo', 'MPV', 'Gasoline', 16, 543, '2010 Maybach 57', 'Maybach', '2010 Maybach 57', 5, '5 Speed Automatic Select Shift', 189, 38, 95, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Audi_TT_Coup%C3%A9_2.0_TFSI_quattro_S-line_%288S%29_%E2%80%93_Frontansicht%2C_3._April_2015%2C_D%C3%BCsseldorf.jpg/400px-Audi_TT_Coup%C3%A9_2.0_TFSI_quattro_S-line_%288S%29_%E2%80%93_Frontansicht%2C_3._April_2015%2C_D%C3%BCsseldorf.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (27, 15, 'Automatic transmission', 'Rear-wheel drive', 'Nissan 4.0L 6 Cylinder 266 hp 288 ft-lbs', 'Hybrid', 'Gasoline', 22, 266, '2009 Nissan Pathfinder LE', 'Nissan', '2009 Nissan Pathfinder', 5, '5 Speed Automatic', 57, 41, 25, 2009, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/VW_Touareg_Exclusive_V6_TDI_BlueMotion_Technology_%28II%29_%E2%80%93_Frontansicht%2C_3._Juli_2013%2C_M%C3%BCnster.jpg/400px-VW_Touareg_Exclusive_V6_TDI_BlueMotion_Technology_%28II%29_%E2%80%93_Frontansicht%2C_3._Juli_2013%2C_M%C3%BCnster.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (28, 13, 'Automatic transmission', 'Rear-wheel drive', 'Ford 4.6L 8 cylinder 225 hp 286 ft-lbs FFV', 'Classic', 'Gasoline', 17, 225, '2011 Ford E-150 Van Commercial', 'Ford', '2011 Ford E-150 Van', 4, '4 Speed Automatic', 224, 44, 128, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Red92VR4rear.jpg/400px-Red92VR4rear.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (29, 17, 'Automatic transmission', 'All-wheel drive', 'Mercedes-Benz 3.0L 6 Cylinder 210 hp 400 ft-lbs Turbo Diesel', '2 WD', 'Diesel fuel', 23, 210, '2010 Mercedes-Benz GL350 BlueTEC 4Matic', 'Mercedes', '2010 Mercedes-Benz GL-Class', 7, '7 Speed Automatic Select Shift', 148, 46, 231, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Cadillac_Cimarron_2_--_07-01-2009.jpg/400px-Cadillac_Cimarron_2_--_07-01-2009.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (30, 17, 'Automatic transmission', 'Front-wheel drive', 'Honda 3.5L 6 Cylinder 250 hp 253 ft-lbs', 'Supercar', 'Gasoline', 23, 250, '2010 Honda Pilot EX', 'Honda', '2010 Honda Pilot', 5, '5 Speed Automatic', 201, 54, 240, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/1991_Daytona_CS.JPG/400px-1991_Daytona_CS.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (31, 17, 'Automatic transmission', 'Rear-wheel drive', 'Infiniti 3.5L 6 cylinder 297 hp 253 ft-lbs', 'Micro', 'Gasoline', 24, 297, '2009 Infiniti EX35', 'Infiniti', '2009 Infiniti EX', 5, '5 Speed Automatic', 11, 54, 22, 2009, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Cadillac_Allante.jpg/400px-Cadillac_Allante.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (32, 14, 'Automatic transmission', 'Front-wheel drive', 'Ford 4.0L 6 Cylinder 210 hp 254 ft-lbs', 'Hybrid', 'Gasoline', 20, 210, '2010 Ford Explorer Eddie Bauer', 'Ford', '2010 Ford Explorer', 5, '5 Speed Automatic', 79, 57, 48, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Toyota_Avensis_III_20090706_front.JPG/400px-Toyota_Avensis_III_20090706_front.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (33, 17, 'Automatic transmission', 'Front-wheel drive', 'Chevrolet 3.6L 6 Cylinder 281 hp 266 ft-lbs', 'Car', 'Gasoline', 24, 281, '2010 Chevrolet Traverse 1LT', 'Chevrolet', '2010 Chevrolet Traverse', 6, '6 Speed Automatic Select Shift', 199, 57, 87, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Mercedes_300SL_Coupe_vr_silver_EMS.jpg/400px-Mercedes_300SL_Coupe_vr_silver_EMS.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (34, 17, 'Automatic transmission', 'Front-wheel drive', 'GMC 3.6L 6 Cylinder 288 hp 270 ft-lbs.', 'Car', 'Gasoline', 24, 288, '2010 GMC Acadia SL', 'GMC', '2010 GMC Acadia', 6, '6 Speed Automatic Select Shift', 194, 57, 233, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Audi_80_B1234.jpg/400px-Audi_80_B1234.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (35, 16, 'Manual transmission', 'Rear-wheel drive', 'Mazda 1.3L R2 232 hp 159 ft-lbs', 'Classic', 'Gasoline', 22, 232, '2010 Mazda RX-8 Grand Touring', 'Mazda', '2010 Mazda RX-8', 6, '6 Speed Manual', 234, 61, 108, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Audi_A2_front_20071002.jpg/400px-Audi_A2_front_20071002.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (36, 11, 'Automatic transmission', 'Rear-wheel drive', 'Rolls-Royce 6.7L 12 Cylinder 453 hp 531 ft-lbs', 'Coupe', 'Gasoline', 18, 453, '2010 Rolls-Royce Phantom Coupe', 'Rolls-Royce', '2010 Rolls-Royce Phantom Coupe', 6, '6 Speed Automatic', 194, 61, 234, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Oldsmobile-Intrigue.jpg/400px-Oldsmobile-Intrigue.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (37, 18, 'Manual transmission', 'All-wheel drive', 'Audi 2.5L 5 Cylinder 360 hp 343 ft-lbs Turbo', 'Minivan', 'Gasoline', 25, 360, '2012 Audi TT RS', 'Audi', '2012 Audi TT RS', 6, '6 Speed Manual', 50, 62, 102, 2012, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/91RT_1.jpg/400px-91RT_1.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (38, 22, 'Manual transmission', 'Front-wheel drive', 'Scion 2.4L 4 Cylinder 158 hp 162 ft-lbs.', 'Antique', 'Gasoline', 28, 158, '2010 Scion xB', 'Scion', '2010 Scion xB', 5, '5 Speed Manual', 224, 64, 153, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/%2782-%2784_Pontiac_6000_Coupe.jpg/400px-%2782-%2784_Pontiac_6000_Coupe.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (39, 18, 'Automatic transmission', 'Four-wheel drive', 'Land Rover 2.0L 4 Cylinder 240 hp 251 ft-lbs', 'Car', 'Gasoline', 28, 240, '2012 Land Rover Range Rover Evoque Coupe Dynamic', 'Land Rover', '2012 Land Rover Range Rover Evoque', 6, '6 Speed Automatic Select Shift', 77, 69, 14, 2012, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Dodge-Shadow-Coupe.jpg/400px-Dodge-Shadow-Coupe.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (40, 20, 'Manual transmission', 'Front-wheel drive', 'Hyundai 2.4L 4 Cylinder 162 hp 162 ft-lbs', '2 WD', 'Gasoline', 28, 162, '2010 Mitsubishi Eclipse GS', 'Mitsubishi', '2010 Mitsubishi Eclipse Coupe', 5, '5 Speed Manual', 41, 71, 230, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Oldsmobile_Alero_sedan_--_03-16-2012.JPG/400px-Oldsmobile_Alero_sedan_--_03-16-2012.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (41, 12, 'Automatic transmission', 'Rear-wheel drive', 'Maserati 4.2L 8 Cylinder 405 hp 339 ft-lbs', '2 WD', 'Gasoline', 19, 405, '2010 Maserati GranTurismo Coup', 'Maserati', '2010 Maserati GranTurismo Coup', 6, '6 Speed Automatic', 123, 73, 17, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/2006_Chrysler_Crossfire_%28ZH_MY05%29_coupe_%282015-11-11%29_01.jpg/400px-2006_Chrysler_Crossfire_%28ZH_MY05%29_coupe_%282015-11-11%29_01.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (42, 12, 'Automatic transmission', 'Rear-wheel drive', 'Maserati 4.7L 8 Cylinder 433 hp 361 ft-lbs', 'Convertible', 'Gasoline', 19, 433, '2010 Maserati GranTurismo Convertible', 'Maserati', '2010 Maserati GranTurismo Convertible', 6, '6 Speed Automatic', 123, 73, 17, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/1968_AMC_AMX_white_at_Rockville_Maryland_show_2007.jpg/400px-1968_AMC_AMX_white_at_Rockville_Maryland_show_2007.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (43, 21, 'Automatic transmission', 'Front-wheel drive', 'Toyota 2.7L 4 Cylinder 182 hp 182 ft-lbs', 'Car', 'Gasoline', 29, 182, '2010 Toyota Venza', 'Toyota', '2010 Toyota Venza', 6, '6 Speed Automatic Select Shift', 113, 74, 192, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/93_Dodge_Dynasty_%2814344073600%29.jpg/400px-93_Dodge_Dynasty_%2814344073600%29.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (44, 12, 'Automatic transmission', 'Rear-wheel drive', 'Ford 5.4L 8 cylinder 255 hp 350 ft-lbs FFV', 'Classic', 'Gasoline', 15, 255, '2011 Ford E-350 Super Duty Van Commercial', 'Ford', '2011 Ford E-350 Super Duty Van', 4, '4 Speed Automatic', 224, 77, 128, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Audi_A5_Coup%C3%A9_2.0_TFSI_quattro_S_tronic_Gletscherwei%C3%9F_Facelift.JPG/400px-Audi_A5_Coup%C3%A9_2.0_TFSI_quattro_S_tronic_Gletscherwei%C3%9F_Facelift.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (45, 15, 'Automatic transmission', 'Rear-wheel drive', 'Chevrolet 4.3L 6 Cylinder 195 hp 525 ft-lbs', 'Minivan', 'Gasoline', 20, 195, '2012 Chevrolet Express 1500', 'Chevrolet', '2012 Chevrolet Express', 4, '4 Speed Automatic', 219, 77, 60, 2012, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/2015_Audi_A4_B9_3.0_TDI_quattro_V6_200_kW_S_line_Tangorot_Vorderansicht_%28cropped%29.jpg/400px-2015_Audi_A4_B9_3.0_TDI_quattro_V6_200_kW_S_line_Tangorot_Vorderansicht_%28cropped%29.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (46, 21, 'Automatic transmission', 'Front-wheel drive', 'Mazda 2.5L 4 Cylinder 157 hp 163 ft-lbs', 'Supercar', 'Gasoline', 28, 157, '2012 Mazda Mazda5 Grand Touring', 'Mazda', '2012 Mazda Mazda5', 5, '5 Speed Automatic Select Shift', 214, 79, 232, 2012, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Cadillac_V-16_Roadster_1930.jpg/400px-Cadillac_V-16_Roadster_1930.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (47, 21, 'Automatic transmission', 'Rear-wheel drive', 'Chevrolet 6.0L 8 Cylinder 332 hp 367 ft-lbs Hybrid', 'Electrical', 'Gasoline', 22, 332, '2009 Chevrolet Silverado 1500 Hybrid 1HY', 'Chevrolet', '2009 Chevrolet Silverado 1500 Hybrid', 4, '4 Speed Automatic', 240, 82, 207, 2009, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Fiero88.JPG/400px-Fiero88.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (48, 21, 'Automatic transmission', 'Rear-wheel drive', 'GMC 6.0L 8 Cylinder 332 hp 367 ft-lbs Hybrid', 'Electrical', 'Gasoline', 22, 332, '2010 GMC Sierra 1500 Hybrid 3HA 2WD', 'GMC', '2010 GMC Sierra 1500 Hybrid', 4, '4 Speed Automatic', 240, 82, 207, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/1990_240sx_Quarter_View.JPG/400px-1990_240sx_Quarter_View.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (49, 14, 'Automatic transmission', 'Rear-wheel drive', 'Chevrolet 4.8L 8 Cylinder 302 hp 305 ft-lbs FFV', 'Micro', 'Gasoline', 19, 302, '2010 Chevrolet Silverado 1500 Crew Cab LS', 'Chevrolet', '2010 Chevrolet Silverado 1500', 4, '4 Speed Automatic', 240, 82, 215, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/2008_Chrysler_300.jpg/400px-2008_Chrysler_300.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (50, 14, 'Automatic transmission', 'Rear-wheel drive', 'GMC 4.8L 8 Cylinder 302 hp 305 ft-lbs FFV', 'Micro', 'Gasoline', 19, 302, '2010 GMC Sierra 1500 Crew Cab Short Box SL 2WD', 'GMC', '2010 GMC Sierra 1500', 4, '4 Speed Automatic', 240, 82, 215, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Volvo_C30_RDesign_HRes.jpg/400px-Volvo_C30_RDesign_HRes.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (51, 12, 'Automatic transmission', 'Four-wheel drive', 'Land Rover 5.0L 8 Cylinder 510 hp 461 ft-lbs S-charged', 'Wagon', 'Gasoline', 18, 510, '2012 Land Rover Range Rover Autobiography', 'Land Rover', '2012 Land Rover Range Rover', 6, '6 Speed Automatic Select Shift', 166, 85, 106, 2012, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Plymouth_Duster_%28Orange_Julep%29.jpg/400px-Plymouth_Duster_%28Orange_Julep%29.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (52, 15, 'Automatic transmission', 'Rear-wheel drive', 'Nissan 4.0L 6 Cylinder 261 hp 281 ft-lbs', 'Mini', 'Gasoline', 20, 261, '2010 Nissan Frontier Crew Cab LE', 'Nissan', '2010 Nissan Frontier', 5, '5 Speed Automatic', 57, 85, 99, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Mazda_Xedos_9.JPG/400px-Mazda_Xedos_9.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (53, 13, 'Automatic transmission', 'Four-wheel drive', 'Toyota 5.7L 8 Cylinder 381 hp 401 ft-lbs', 'Car', 'Gasoline', 18, 381, '2010 Toyota Land Cruiser', 'Toyota', '2010 Toyota Land Cruiser', 6, '6 Speed Automatic Select Shift', 179, 88, 87, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Fiat_Tempra_SX_%2793.jpg/400px-Fiat_Tempra_SX_%2793.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (54, 14, 'Manual transmission', 'All-wheel drive', 'Audi 4.2L 8 cylinder 354hp 325 ft-lbs', 'Coupe', 'Gasoline', 22, 354, '2010 Audi S5 Coupe 4.2', 'Audi', '2010 Audi S5 Coupe', 6, '6 Speed Manual', 62, 89, 27, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Opel_Calibra_front_20071007.jpg/400px-Opel_Calibra_front_20071007.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (55, 16, 'Manual transmission', 'All-wheel drive', 'Audi 3.2L 6 cylinder 265hp 243 ft-lbs', 'Car', 'Gasoline', 27, 265, '2009 Audi A5 3.2', 'Audi', '2009 Audi A5', 6, '6 Speed Manual', 62, 91, 17, 2009, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/2001-2005_Peugeot_307_%28T5%29_5-door_hatchback_%282011-03-10%29.jpg/400px-2001-2005_Peugeot_307_%28T5%29_5-door_hatchback_%282011-03-10%29.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (56, 20, 'Manual transmission', 'Rear-wheel drive', 'Lotus 1.8L 4 Cylinder 218 hp 156 ft-lbs S-charged', '2 WD', 'Gasoline', 26, 218, '2010 Lotus Elise SC', 'Lotus', '2010 Lotus Elise', 6, '6 Speed Manual', 183, 93, 200, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/2005_Peugeot_407_ST_HDi_Executive_sedan_%282015-07-09%29_01.jpg/400px-2005_Peugeot_407_ST_HDi_Executive_sedan_%282015-07-09%29_01.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (57, 21, 'Manual transmission', 'Rear-wheel drive', 'Lotus 1.8L 4 Cylinder 189 hp 133 ft-lbs', 'Hybrid', 'Gasoline', 27, 189, '2009 Lotus Elise', 'Lotus', '2009 Lotus Elise', 6, '6 Speed Manual', 183, 93, 200, 2009, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Simca_Chrysler_Horizon_GLS_1979.jpg/400px-Simca_Chrysler_Horizon_GLS_1979.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (58, 21, 'Automatic transmission', 'Front-wheel drive', 'Mazda 2.3L 4 Cylinder 153 hp 148 ft-lbs', 'MPV', 'Gasoline', 27, 153, '2010 Mazda Mazda5 Grand Touring', 'Mazda', '2010 Mazda Mazda5', 5, '5 Speed Automatic Select Shift', 216, 94, 2, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/OPEL-VAUX-SINTRA-A.jpg/400px-OPEL-VAUX-SINTRA-A.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (59, 14, 'Manual transmission', 'Rear-wheel drive', 'BMW 4.8L 8 cylinder 360hp 360 ft-lbs', 'Car', 'Gasoline', 21, 360, '2010 BMW 650i Convertible MT', 'BMW', '2010 BMW 6 Series Convertible', 6, '6 Speed Manual', 62, 94, 223, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Fiat_Stilo_front_20080711.jpg/400px-Fiat_Stilo_front_20080711.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (60, 12, 'Automatic transmission', 'Four-wheel drive', 'Land Rover 5.0L 8 Cylinder 375 hp 375 ft-lbs', 'Electrical', 'Gasoline', 17, 375, '2010 Land Rover LR4 V8', 'Land Rover', '2010 Land Rover LR4', 6, '6 Speed Automatic Select Shift', 123, 95, 220, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Ford_Fairmont_sedan_2.jpg/400px-Ford_Fairmont_sedan_2.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (61, 11, 'Manual transmission', 'Rear-wheel drive', 'BMW 5.0L 10 cylinder 500hp 383 ft-lbs', 'Car', 'Gasoline', 17, 500, '2010 BMW M6 Convertible MT', 'BMW', '2010 BMW M6 Convertible', 6, '6 Speed Manual', 62, 96, 7, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/1990_Dodge_Omni.JPG/400px-1990_Dodge_Omni.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (62, 17, 'Manual transmission', 'Rear-wheel drive', 'Chevrolet 3.6L 6 Cylinder 304 hp 273 ft-lbs', 'Car', 'Gasoline', 29, 304, '2010 Chevrolet Camaro Coupe 1LS', 'Chevrolet', '2010 Chevrolet Camaro Coupe', 6, '6 Speed Manual', 125, 96, 228, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/00-02_Saturn_L-Series_sedan.jpg/400px-00-02_Saturn_L-Series_sedan.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (63, 12, 'Automatic transmission', 'All-wheel drive', 'Bentley 6.0L 12 Cylinder 621 hp 590 ft-lbs FFV Turbo', 'Sports', 'Gasoline', 19, 621, '2010 Bentley Continental Supersports', 'Bentley', '2010 Bentley Continental Supersports', 6, '6 Speed Automatic', 153, 99, 195, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Saturn_Ion_--_07-09-2009.jpg/400px-Saturn_Ion_--_07-09-2009.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (64, 21, 'Manual transmission', 'Front-wheel drive', 'Kia 2.4L 4 Cylinder 176 hp 168 ft-lbs', 'Sports', 'Gasoline', 29, 176, '2011 Kia Sportage', 'Kia', '2011 Kia Sportage', 6, '6 Speed Manual', 62, 99, 87, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/1996-1999_Saturn_SL2_--_03-16-2012.JPG/400px-1996-1999_Saturn_SL2_--_03-16-2012.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (65, 21, 'Manual transmission', 'Rear-wheel drive', 'Hyundai 2.0L 4 Cylinder 210 hp 223 ft-lbs Turbo', 'Coupe', 'Gasoline', 30, 210, '2010 Hyundai Genesis Coupe 2.0T', 'Hyundai', '2010 Hyundai Genesis Coupe', 6, '6 Speed Manual', 72, 104, 22, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Chrysler_E_Class%2C_1984.png/400px-Chrysler_E_Class%2C_1984.png');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (66, 17, 'Manual transmission', 'Rear-wheel drive', 'Chevrolet 3.6L 6 Cylinder 312 hp 278 ft-lbs', 'Convertible', 'Gasoline', 28, 312, '2011 Chevrolet Camaro Convertible 1LT', 'Chevrolet', '2011 Chevrolet Camaro Convertible', 6, '6 Speed Manual', 125, 109, 228, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Plymouth_Caravelle%2C_83-85.png/400px-Plymouth_Caravelle%2C_83-85.png');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (67, 17, 'Manual transmission', 'Rear-wheel drive', 'Chevrolet 3.6L 6 Cylinder 323 hp 278 ft-lbs', 'Minivan', 'Gasoline', 28, 323, '2012 Chevrolet Camaro Convertible 1LT', 'Chevrolet', '2012 Chevrolet Camaro Convertible', 6, '6 Speed Manual', 125, 109, 228, 2012, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/1984_Dodge_600_ES_Turbo.jpg/400px-1984_Dodge_600_ES_Turbo.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (68, 20, 'Automatic transmission', 'Front-wheel drive', 'Mazda 2.5L 4 Cylinder 161 hp 161 ft-lbs', 'Sports', 'Gasoline', 28, 161, '2010 Mazda CX-7 i Sport', 'Mazda', '2010 Mazda CX-7', 5, '5 Speed Automatic Select Shift', 79, 109, 73, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/%2782_Dodge_400_Coupe_%28Orange_Julep%29.JPG/400px-%2782_Dodge_400_Coupe_%28Orange_Julep%29.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (69, 13, 'Manual transmission', 'Rear-wheel drive', 'BMW 4.0L 8 cylinder 414 hp 295 ft-lbs', 'Coupe', 'Gasoline', 20, 414, '2010 BMW M3 Convertible', 'BMW', '2010 BMW M3 Convertible', 6, '6 Speed Manual', 11, 111, 7, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/1990_Plymouth_Laser_RS_Turbo_red.jpg/400px-1990_Plymouth_Laser_RS_Turbo_red.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (70, 19, 'Automatic transmission', 'Rear-wheel drive', 'Infiniti 3.7L 6 cylinder 330 hp 270 ft-lbs', 'Coupe', 'Gasoline', 27, 330, '2010 Infiniti G37 Coupe', 'Infiniti', '2010 Infiniti G37 Coupe', 7, '7 Speed Automatic', 31, 111, 42, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/2002-2004_Chrysler_300M_--_05-23-2012.JPG/400px-2002-2004_Chrysler_300M_--_05-23-2012.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (71, 31, 'Manual transmission', 'Front-wheel drive', 'Honda 1.5L 4 Cylinder 122hp 128lb-ft Hybrid', 'Electrical', 'Gasoline', 37, 122, '2011 Honda CR-Z', 'Honda', '2011 Honda CR-Z', 6, '6 Speed Manual', 203, 114, 239, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/1995_Vision_TSi_sedan.jpg/400px-1995_Vision_TSi_sedan.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (72, 19, 'Automatic transmission', 'Rear-wheel drive', 'Infiniti 3.7L 6 Cylinder 348 hp 276 ft-lbs', 'Minivan', 'Gasoline', 27, 348, '2011 Infiniti IPL G Coupe', 'Infiniti', '2011 Infiniti IPL G Coupe', 7, '7 Speed Automatic', 31, 114, 93, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Chrysler-Concorde-Limited.jpg/400px-Chrysler-Concorde-Limited.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (73, 24, 'Manual transmission', 'Front-wheel drive', 'Nissan 1.8L 4 Cylinder 122 hp 127 ft-lbs', 'Hybrid', 'Gasoline', 29, 122, '2009 Nissan Cube 1.8', 'Nissan', '2009 Nissan Cube', 6, '6 Speed Manual', 158, 115, 140, 2009, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/1992_Eagle_Premier_ES_Limited.jpg/400px-1992_Eagle_Premier_ES_Limited.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (74, 14, 'Automatic transmission', 'Rear-wheel drive', 'Dodge 5.7L 8 Cylinder 390 hp 407 ft-lbs', 'Micro', 'Gasoline', 20, 390, '2010 Dodge Ram 1500 Laramie Crew Cab 4x2', 'Dodge', '2010 Dodge Ram 1500', 5, '5 Speed Automatic', 224, 115, 184, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Lancia_Thema_8.32_Ferrari.jpg/400px-Lancia_Thema_8.32_Ferrari.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (75, 17, 'Automatic transmission', 'Front-wheel drive', 'Volkswagen 3.6L 6 Cylinder 283 hp 260 ft-lbs', 'MPV', 'Gasoline', 25, 283, '2011 Volkswagen Routan S', 'Volkswagen', '2011 Volkswagen Routan', 6, '6 Speed Automatic', 161, 115, 23, 2011, 'https://upload.wikimedia.org/wikipedia/en/7/7e/76_Pontiac_Astre.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (76, 26, 'Manual transmission', 'Front-wheel drive', 'Honda 1.8L 4 Cylinder 140hp 128 ft-lbs', 'Supercar', 'Gasoline', 34, 140, '2010 Honda Civic DX Coup', 'Honda', '2010 Honda Civic Coup', 5, '5 Speed Manual', 214, 117, 105, 2010, 'https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Vega_clay_model.jpg/400px-Vega_clay_model.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (77, 18, 'Automatic transmission', 'All-wheel drive', 'Audi 3.2L 6 cylinder 270 hp 243 ft-lbs', 'MPV', 'Gasoline', 23, 270, '2009 Audi Q5 3.2', 'Audi', '2009 Audi Q5', 6, '6 Speed Automatic Select Shift', 88, 117, 20, 2009, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Oldsmobile_Firenza_coupe_2.jpg/400px-Oldsmobile_Firenza_coupe_2.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (78, 8, 'Automatic transmission', 'All-wheel drive', 'Bentley 6.0L 12 Cylinder 552 hp 479 ft-lbs FFV Turbo', 'MPV', 'E85', 13, 552, '2012 Bentley Continental Flying Spur', 'Bentley', '2012 Bentley Continental Flying Spur', 6, '6 Speed Automatic', 184, 118, 170, 2012, 'https://upload.wikimedia.org/wikipedia/commons/1/18/75_Chevy_Monza_2%2B2.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (79, 17, 'Automatic transmission', 'Rear-wheel drive', 'Infiniti 3.7L 6 Cylinder 325 hp 267 ft-lbs', 'Antique', 'Gasoline', 25, 325, '2009 Infiniti G37 Convertible', 'Infiniti', '2009 Infiniti G37 Convertible', 7, '7 Speed Automatic', 59, 119, 47, 2009, 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/BMW_6er_Coup%C3%A9_Facelift_20090808_front.JPG/400px-BMW_6er_Coup%C3%A9_Facelift_20090808_front.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (80, 17, 'Manual transmission', 'Rear-wheel drive', 'Ford 5.0L 8 Cylinder 444 hp 380 ft-lbs', 'Crossover', 'Gasoline', 26, 444, '2012 Ford Mustang Boss 302', 'Ford', '2012 Ford Mustang Coup', 6, '6 Speed Manual', 85, 119, 169, 2012, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Chevrolet_Citation_II_front.jpg/400px-Chevrolet_Citation_II_front.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (81, 19, 'Automatic transmission', 'Front-wheel drive', 'Acura 2.3L 4 Cylinder 240 hp 260 ft-lbs TURBO', 'Hybrid', 'Gasoline', 24, 240, '2010 Acura RDX', 'Acura', '2010 Acura RDX', 5, '5 Speed Automatic Select Shift', 78, 119, 27, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/96-98_Mercury_Villager_--_12-26-2009.jpg/400px-96-98_Mercury_Villager_--_12-26-2009.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (82, 23, 'Manual transmission', 'Four-wheel drive', 'Jeep 2.4L 4 Cylinder 172 hp 165 ft-lbs', '4 WD', 'Gasoline', 28, 172, '2010 Jeep Compass Limited 4x4', 'Jeep', '2010 Jeep Compass', 5, '5 Speed Manual', 224, 120, 52, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Nissan350Z-01.jpg/400px-Nissan350Z-01.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (83, 22, 'Manual transmission', 'Front-wheel drive', 'Hyundai 2.4L 4 Cylinder 176 hp 168 ft-lbs', '4 WD', 'Gasoline', 30, 176, '2010 Hyundai Tucson GLS', 'Hyundai', '2010 Hyundai Tucson', 6, '6 Speed Manual', 29, 120, 47, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Hummer_H2_black.JPG/400px-Hummer_H2_black.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (84, 23, 'Manual transmission', 'Front-wheel drive', 'Jeep 2.0L 4 Cylinder 158 hp 141 ft-lbs', 'Sports', 'Gasoline', 29, 158, '2011 Jeep Compass Sport 4x2', 'Jeep', '2011 Jeep Compass', 5, '5 Speed Manual', 224, 120, 52, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Cadillac_XLR_2006.jpg/400px-Cadillac_XLR_2006.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (85, 18, 'Automatic transmission', 'Rear-wheel drive', 'Chevrolet 2.9L 4 Cylinder 185 hp 190 ft-lbs', 'Micro', 'Gasoline', 25, 185, '2010 Chevrolet Colorado Crew Cab LT1', 'Chevrolet', '2010 Chevrolet Colorado', 4, '4 Speed Automatic', 181, 120, 140, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Cadillac--STS.jpg/400px-Cadillac--STS.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (86, 18, 'Automatic transmission', 'Rear-wheel drive', 'GMC 2.9L 4 Cylinder 185 hp 190 ft-lbs', 'Micro', 'Gasoline', 25, 185, '2010 GMC Canyon Crew Cab SLE 2WD', 'GMC', '2010 GMC Canyon', 4, '4 Speed Automatic', 181, 120, 140, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/04-07_Buick_Rendezvous_.jpg/400px-04-07_Buick_Rendezvous_.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (87, 8, 'Automatic transmission', 'All-wheel drive', 'Bentley 6.0L 12 Cylinder 567 hp 516 ft-lbs FFV', 'Car', 'E85', 14, 567, '2012 Bentley Continental GT', 'Bentley', '2012 Bentley Continental GT', 6, '6 Speed Automatic Select Shift', 152, 124, 198, 2012, 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/CT2007SciontC.jpg/400px-CT2007SciontC.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (88, 19, 'Automatic transmission', 'All-wheel drive', 'BMW 3.0L 6 cylinder 240hp 221 ft-lbS', 'Car', 'Gasoline', 25, 240, '2011 BMW X3 xDrive28i SUV', 'BMW', '2011 BMW X3', 8, '8 Speed Automatic Select Shift', 90, 125, 40, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/97-99_Cadillac_Catera_.jpg/400px-97-99_Cadillac_Catera_.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (89, 18, 'Manual transmission', 'All-wheel drive', 'Audi 3.0L 6 Cylinder 333 hp 325 ft-lbs S-charged', 'Hybrid', 'Gasoline', 27, 333, '2010 Audi S4 Sedan 3.0', 'Audi', '2010 Audi S4 Sedan', 6, '6 Speed Manual', 34, 126, 109, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Fiat_Coup%C3%A9_front_20090604.jpg/400px-Fiat_Coup%C3%A9_front_20090604.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (90, 12, 'Automatic transmission', 'Four-wheel drive', 'Lexus 5.7L 8 Cylinder 383hp 403 ft-lbs', '2 WD', 'Gasoline', 18, 383, '2010 Lexus LX 570 SUV', 'Lexus', '2010 Lexus LX', 6, '6 Speed Automatic Select Shift', 179, 128, 127, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/2002-05_Pontiac_Aztek.jpg/400px-2002-05_Pontiac_Aztek.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (91, 14, 'Automatic transmission', 'Rear-wheel drive', 'Jeep 5.7L 8 Cylinder 357 hp 389 ft-lbs', '4 WD', 'Gasoline', 20, 357, '2010 Jeep Commander Limited', 'Jeep', '2010 Jeep Commander', 5, '5 Speed Automatic Select Shift', 107, 128, 179, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Mercury-Milan-Premier.JPG/400px-Mercury-Milan-Premier.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (92, 14, 'Automatic transmission', 'Rear-wheel drive', 'Infiniti 5.6L 8 Cylinder 400 hp 413 ft-lbs', 'Car', 'Gasoline', 20, 400, '2011 Infiniti QX56 2WD', 'Infiniti', '2011 Infiniti QX56', 7, '7 Speed Automatic', 237, 128, 170, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Audi_Quattro_vl_black.jpg/400px-Audi_Quattro_vl_black.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (93, 16, 'Manual transmission', 'Rear-wheel drive', 'Ford 4.6L 8 Cylinder 315 hp 325 ft-lbs', 'Hybrid', 'Gasoline', 24, 315, '2010 Ford Mustang GT', 'Ford', '2010 Ford Mustang Coup', 5, '5 Speed Manual', 85, 132, 169, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Volvo_V40_2012_ID42221_280212.jpg/400px-Volvo_V40_2012_ID42221_280212.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (94, 18, 'Automatic transmission', 'Front-wheel drive', 'Cadillac 3L 6 Cylinder 265 hp 223 ft-lbs', 'Car', 'Gasoline', 25, 265, '2010 Cadillac SRX', 'Cadillac', '2010 Cadillac SRX', 6, '6 Speed Automatic Select Shift', 118, 132, 225, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/LincolnAviator.jpg/400px-LincolnAviator.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (95, 12, 'Automatic transmission', 'Front-wheel drive', 'Cadillac 3.6L  6 Cylinder 308 hp 265 ft-lbs FFV', 'Car', 'E85', 18, 308, '2012 Cadillac SRX Crossover', 'Cadillac', '2012 Cadillac SRX Crossover', 6, '6 Speed Automatic Select Shift', 118, 132, 225, 2012, 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/00-02_Lincoln_LS_.jpg/400px-00-02_Lincoln_LS_.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (96, 18, 'Manual transmission', 'Rear-wheel drive', 'BMW 3.0L 6 cylinder 230hp 200 ft-lbs', 'Car', 'Gasoline', 28, 230, '2010 BMW 128i Convertible', 'BMW Motorrad', '2010 BMW 1 Series Convertible', 6, '6 Speed Manual', 211, 132, 9, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/2002_Lincoln_Blackwood_2.jpg/400px-2002_Lincoln_Blackwood_2.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (97, 15, 'Automatic transmission', 'Rear-wheel drive', 'Toyota 4.0L 6 Cylinder 236 hp 266 ft-lbs', 'MPV', 'Gasoline', 19, 236, '2010 Toyota Tundra', 'Toyota', '2010 Toyota Tundra', 5, '5 Speed Automatic Select Shift', 237, 133, 208, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/89mark.jpg/400px-89mark.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (98, 12, 'Automatic transmission', 'Rear-wheel drive', 'Mercedes-Benz 6.2L 8 Cylinder 507 hp 465 ft-lbs', 'Car', 'Gasoline', 18, 507, '2011 Mercedes-Benz CLS63 AMG', 'Mercedes-AMG', '2011 Mercedes-Benz CLS-Class', 7, '7 Speed Automatic Select Shift', 79, 134, 53, 2011, 'https://upload.wikimedia.org/wikipedia/en/thumb/2/29/Mark_VIII.JPG/400px-Mark_VIII.JPG');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (99, 21, 'Automatic transmission', 'Rear-wheel drive', 'Cadillac 6.0L 8 Cylinder 332 hp 367 ft-lbs Hybrid', 'Electrical', 'Gasoline', 22, 332, '2010 Cadillac Escalade Hybrid', 'Cadillac', '2010 Cadillac Escalade Hybrid', 4, '4 Speed Automatic Select Shift', 214, 135, 23, 2010, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Ford_Aerostar_LWB_1992-97.jpg/400px-Ford_Aerostar_LWB_1992-97.jpg');
INSERT INTO `cars` (`id`, `city_miles_per_gallon`, `classification`, `driveline`, `engine_type`, `type`, `fuel_type`, `highway_miles_per_gallon`, `horsepower`, `model_id`, `make`, `model_year`, `number_of_forward_gears`, `transmission`, `width`, `height`, `length`, `year`, `image_uri`) VALUES (100, 15, 'Automatic transmission', 'Rear-wheel drive', 'Ford 5.0L 8 Cylinder 360 hp 380 ft-lbs FFV', 'Vintage', 'Gasoline', 21, 360, '2011 Ford F-150 FX2 SuperCab 6.5-ft. Bed', 'Ford', '2011 Ford F-150', 6, '6 Speed Automatic Select Shift', 212, 135, 253, 2011, 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Vw_t3_s_sst.jpg/400px-Vw_t3_s_sst.jpg');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
